### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by GYF0404** [davidcarslaw/deweather#14]
I want to know the input unit is **ppb**, and finally how to convert it to **μg/m³**.

**Comment by jack-davison** [comment]
Afternoon,

`{deweather}` doesn't pay any attention to units - your input could be ppb or ug/m3, temperature can be C, F, or K, etc. The units you put in are the units you get out.

There are a lot of articles online for converting between units that describe the calculations in a lot more detail than we can provide here, for example: 

https://www.breeze-technologies.de/blog/air-pollution-how-to-convert-between-mgm3-%C2%B5gm3-ppm-ppb/

https://uk-air.defra.gov.uk/assets/documents/reports/cat06/0502160851_Conversion_Factors_Between_ppb_and.pdf

Hope this helps!
Jack

**Comment by GYF0404** [comment]
Thank you for your response! I have another question. When I perform ten-fold cross-validation, the results only inform me that the best performance is achieved at 300 iterations, but it doesn't provide any performance metrics. I would like to ask how to address this issue.
