### ISSUE TITLE
Issue installing deweather

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/deweather#2]
Hi David, 

I am having an issue with installing this package - I have previously had it installed but my system has recently had a clear out so I am starting a fresh.  

I have tried running:

library(devtools)
Error: package or namespace load failed for ‘devtools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘callr’
In addition: Warning message:
package ‘devtools’ was built under R version 3.6.3 
> install_github("davidcarslaw/deweather")
Error in install_github("davidcarslaw/deweather") : 
  could not find function "install_github"

Is it simply that my version of R is too outdated now?

**Comment by jmclaren17** [comment]
When I try to install 'callr' it gives this message

**Comment by jmclaren17** [comment]
> install.packages("callr")

  There is a binary version available but the source version is later:
      binary source needs_compilation
callr  3.4.4  3.5.0             FALSE

installing the source package ‘callr’

trying URL 'https://cran.rstudio.com/src/contrib/callr_3.5.0.tar.gz'
Content type 'application/x-gzip' length 77205 bytes (75 KB)
downloaded 75 KB

* installing *source* package 'callr' ...
** package 'callr' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'processx', details:
  call: loadNamespace(name)
  error: there is no package called 'ps'
Execution halted
ERROR: lazy loading failed for package 'callr'
* removing 'C:/Program Files/The R Foundation/R 3.6.2/library/callr'
Warning in install.packages :
  installation of package ‘callr’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\MCLA1087\AppData\Local\Temp\RtmpQRgEeY\downloaded_packages’

**Comment by jmclaren17** [comment]
The version of R that is running is 3.6.2

**Comment by jack-davison** [comment]
Hi, 

Going to close this as it's a pretty old issue.

Nowadays I'd recommend `{pak}` over `{devtools}` as it is much more lightweight.

```r
# install.packages("pak")
pak::pak("davidcarslaw/deweather")
```
