### ISSUE TITLE
[Bug]: Plots not showing for testMod()

### ISSUE THREAD

**Issue by Roset999** [davidcarslaw/deweather#28]
I have recently updated to R 4.4.2 and since then, my testMod() function no longer produces an image showing the model performance parameters. It does run, and reports the percent increase in RMSE using test data in the console.  

This is the function as run:
testMod(
  NZSTC_subset, #dataset of 1-hour met and TSP, ten years
  vars = c("trend", "ws", "wd",  "Temp", "RH", "rain24hrmm_rolling"),
  pollutant = "TSP",
  n.trees = 300
)

Previously, it would produce a plot like this:
![image](https://github.com/user-attachments/assets/5ad650ed-f9a5-41a1-b827-6ee267cef975)

I have rolled R back to 4.4.1 but continue to have the same issue. I am not actually sure what version I was using previously but my coworker uses 4.4.1 and her deweather plots work fine.

---

Here's what I get when I run my code and then run reprex() - not sure if this has worked as intended, first time using reprex:

```r
``` r
Percent increase in RMSE using test data 
#> Error in parse(text = input): <text>:1:9: unexpected symbol
#> 1: Percent increase
#>             ^
```

<sup>Created on 2024-11-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

```

**Comment by jack-davison** [comment]
Hi Roset999,

First - reprex is just one way to provide a reproducible example. It makes sure you've provided everything needed to recreate your issue on someone else's machine. For example, I wrote this code, copy-pasted, and then ran `reprex::reprex()` which formatted this output for me:

``` r
library(openair)
#> Warning: package 'openair' was built under R version 4.3.3

windRose(mydata)
```

![](https://i.imgur.com/KbZh09O.png)

<sup>Created on 2024-11-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

You have provided:

> ``` r
> Percent increase in RMSE using test data 
> #> Error in parse(text = input): <text>:1:9: unexpected symbol
> #> 1: Percent increase
> #>             ^
> 

Which I can't do a lot with!

Regardless, I think I've fixed your issue. Please re-download the package from GitHub and see if it works now :-)

``` r
deweather::testMod(deweather::road_data[1:100,])
#> ℹ Optimum number of trees is 4479
#> ℹ RMSE from cross-validation is 105.72
#> ℹ Percent increase in RMSE using test data is 75.0%
```

![](https://i.imgur.com/yvcDLYT.png)

<sup>Created on 2024-11-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Roset999** [comment]
Thanks Jack - you're right, I'm not sure what I thought you'd be able to do with that reprex!
In any case, your package update has fixed my issue :)
Thank you!
