### ISSUE TITLE
Remove concentration levels trend of previous years

### ISSUE THREAD

**Issue by sancebsan** [davidcarslaw/deweather#3]
When it is used metSin function to predict NO2 concentrations without the influence of meteorological variables, the explanation of the example says that:  there is no need to supply the "trend" component because it´s calculated through the function metSim. 
So, that means that metSim function subtracts internally the trend of NO2 concentration levels from previous years?

Tank you in advance for your help.

**Comment by davidcarslaw** [comment]
Hi - the best way to think about this is that `metSim` tries to provide an average trend while accounting for the variation in variables provided by the option `metVars` and does this through random sampling of the whole data set. The trend component is calculate for each simulation based on the model developed by `buildMod`.  So, for example, if you wanted an estimate of the trend under average wind speed conditions (determined by randomly sampling from the whole data set), you would just supply the option `metVars = "ws"`. Usually though, you want to control for more weather variables such as wind direction, temperature etc. Does that help?
