### ISSUE TITLE
Error in as.POSIXlt.character

### ISSUE THREAD

**Issue by judismch** [davidcarslaw/deweather#4]
Hi David

When I run **testMod()**
Shows me the following error :

> testMod(dat = dat_part, 
vars = c("trend", "ws", "wd", "hour", "weekday", "air_temp", "week"),
pollutant = "no2")

**Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format**

what should I do? **Can you solve my problem?**

Thank you

**Comment by davidcarslaw** [comment]
I suspect this is because the date has not been formatted correctly. What does `summary(dat_part$date)` look like?

**Comment by jack-davison** [comment]
Closing stale issue (~3 years).
