### ISSUE TITLE
MetSim issue with latest commit

### ISSUE THREAD

**Issue by djg46** [davidcarslaw/deweather#6]
Hi,

I have a dataset with ~60,000 points which I am detrending. When I install from the commit made on February 8th, 2022, MetSim produces a dataframe with the same number of observations as in the original dataset. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/115170687/234654293-df3a694e-cde1-4d11-965a-0f0e891c1e93.png">
Above: Output using Feb 22 commit

However, when using deweather installed from the latest commit, the same code returns over 12 million rows, with the dates running through the full expected sequence but then repeating.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/115170687/234656058-adcce63f-cbc0-40ba-956b-8618690e8a6e.png">
Above: Output using latest commit

My code is `below:

`no2_mod <- buildMod(
  data,
  vars = c("trend", "RH", "air_temp", "ws", "wd", "hour", "weekday",
           "week", "month"),
  pollutant = "NO2",
  n.core = 6,
  seed = 92256)`

`no2_detrend <- metSim(
  no2_mod,
  newdata = data,
  metVars = c("RH", "air_temp", "ws", "wd", "hour", "weekday",
              "week", "month"))`

Not sure what could be causing this issue, so thought I would flag it. I am using R 4.3.0. 

Please let me know if I can be of any help.

**Comment by davidcarslaw** [comment]
Thanks Doug. I will have to investigate this. There are some weird date-time things happening in `openair` that I am investigating following a recent R update. I'm away the next couple of days but will sort out when I get back...

David
